import { db } from "../config/db.js";
import {
  role,
  skinConditions,
  users,
  skinProfile,
  skinCareProducts,
  conditionProducts,
} from "./schema.js";
import bcrypt from "bcryptjs";
import { sql } from "drizzle-orm";

export async function main() {
  console.log("Seeding database...");

  await db.execute(sql`SET FOREIGN_KEY_CHECKS = 0`);
  await db.execute(sql`TRUNCATE TABLE reminder_logs`);
  await db.execute(sql`TRUNCATE TABLE user_routine`);
  await db.execute(sql`TRUNCATE TABLE product_recommendations`);
  await db.execute(sql`TRUNCATE TABLE skin_analysis`);
  await db.execute(sql`TRUNCATE TABLE stored_images`);
  await db.execute(sql`TRUNCATE TABLE condition_products`);
  await db.execute(sql`TRUNCATE TABLE skin_care_products`);
  await db.execute(sql`TRUNCATE TABLE skin_profile`);
  await db.execute(sql`TRUNCATE TABLE journals`);
  await db.execute(sql`TRUNCATE TABLE otp`);
  await db.execute(sql`TRUNCATE TABLE users`);
  await db.execute(sql`TRUNCATE TABLE skin_conditions`);
  await db.execute(sql`TRUNCATE TABLE role`);
  await db.execute(sql`SET FOREIGN_KEY_CHECKS = 1`);

  const now = new Date().toISOString().slice(0, 19).replace("T", " ");
  const adminPassword = await bcrypt.hash("admin", 10);
  const userPassword = await bcrypt.hash("user", 10);

  await db.insert(role).values([
    { id: 1, roleName: "admin" },
    { id: 2, roleName: "user" },
  ]);

await db.insert(skinConditions).values([
  // MILD / MODERATE (Can Recommend)
  { id: 1, condition: "acne-blackheads-mild", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Adapalene, Retinol, Retinoids" },
  { id: 2, condition: "acne-blackheads-moderate", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Adapalene, Retinol, Retinoids" },
  { id: 3, condition: "acne-whiteheads-mild", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Adapalene, Retinol, Retinoids" },
  { id: 4, condition: "acne-whiteheads-moderate", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Adapalene, Retinol, Retinoids" },
  { id: 5, condition: "acne-papules-mild", canRecommend: "Yes", targetIngredients: "Benzoyl Peroxide, Retinol, Clindamycin, Retinoids" },
  { id: 6, condition: "acne-papules-moderate", canRecommend: "Yes", targetIngredients: "Benzoyl Peroxide, Retinol, Clindamycin, Retinoids" },
  { id: 7, condition: "acne-pustules-mild", canRecommend: "Yes", targetIngredients: "Benzoyl Peroxide, Retinol, Clindamycin, Retinoids" },
  { id: 8, condition: "acne-pustules-moderate", canRecommend: "Yes", targetIngredients: "Benzoyl Peroxide, Retinol, Clindamycin, Retinoids" },
  { id: 9, condition: "eczema-mild", canRecommend: "Yes", targetIngredients: "Oats, Lipids, Zinc Oxide, Emollients" },
  { id: 10, condition: "eczema-moderate", canRecommend: "Yes", targetIngredients: "Oats, Lipids, Zinc Oxide, Emollients" },
  { id: 11, condition: "melasma-mild", canRecommend: "Yes", targetIngredients: "Kojic Acid, Glutathione, Vitamin C" },
  { id: 12, condition: "melasma-moderate", canRecommend: "Yes", targetIngredients: "Kojic Acid, Glutathione, Vitamin C" },
  { id: 13, condition: "melasma-severe", canRecommend: "Yes", targetIngredients: "Kojic Acid, Glutathione, Vitamin C" },
  { id: 14, condition: "milia-mild", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Retinol" },
  { id: 15, condition: "milia-moderate", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Retinol" },
  { id: 16, condition: "enlarged-pores-mild", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Adapalene" },
  { id: 17, condition: "enlarged-pores-moderate", canRecommend: "Yes", targetIngredients: "Salicylic Acid, Adapalene" },
  { id: 18, condition: "post-inflammatory-hyperpigmentation-mild", canRecommend: "Yes", targetIngredients: "Vitamin C, Arbutin, Niacinamide, Glycolic Acid" },
  { id: 19, condition: "post-inflammatory-hyperpigmentation-moderate", canRecommend: "Yes", targetIngredients: "Vitamin C, Arbutin, Niacinamide, Glycolic Acid" },
  { id: 20, condition: "post-inflammatory-erythema-mild", canRecommend: "Yes", targetIngredients: "Azelaic Acid, Glycolic Acid, Vitamin C" },
  { id: 21, condition: "post-inflammatory-erythema-moderate", canRecommend: "Yes", targetIngredients: "Azelaic Acid, Glycolic Acid, Vitamin C" },

  // SEVERE / MEDICAL (Cannot Recommend)
  { id: 22, condition: "milia-severe", canRecommend: "No", targetIngredients: null },
  { id: 23, condition: "enlarged-pores-severe", canRecommend: "No", targetIngredients: null },
  { id: 24, condition: "acne-blackheads-severe", canRecommend: "No", targetIngredients: null },
  { id: 25, condition: "acne-papules-severe", canRecommend: "No", targetIngredients: null },
  { id: 26, condition: "acne-pustules-severe", canRecommend: "No", targetIngredients: null },
  { id: 27, condition: "acne-whiteheads-severe", canRecommend: "No", targetIngredients: null },
  { id: 28, condition: "acne-cyst", canRecommend: "No", targetIngredients: null },
  { id: 29, condition: "acne-nodules", canRecommend: "No", targetIngredients: null },
  { id: 30, condition: "psoriasis", canRecommend: "No", targetIngredients: null },
  { id: 31, condition: "eczema-severe", canRecommend: "No", targetIngredients: null },
  { id: 32, condition: "post-inflammatory-erythema-severe", canRecommend: "No", targetIngredients: null },
  { id: 33, condition: "post-inflammatory-hyperpigmentation-severe", canRecommend: "No", targetIngredients: null },
  { id: 34, condition: "out-of-scope", canRecommend: "No", targetIngredients: null },
  { id: 35, condition: "acne-fungal-mild", canRecommend: "Yes", targetIngredients: "Ketoconazole, Nizoral" },
  { id: 36, condition: "acne-fungal-severe", canRecommend: "No", targetIngredients: null },
]);
//adapalene, benzoid peroxide, and clindamycin is what i put there as not for sensitive

  await db.insert(users).values([
    {
      id: 1,
      firstName: "firstadmin",
      lastName: "lastadmin",
      email: "admin@a.c",
      password: adminPassword,
      roleId: 1,
      birthdate: "2000-01-01",
      updatedAt: now,
    },
    {
      id: 2,
      firstName: "firstuser",
      lastName: "lastuser",
      email: "user@a.c",
      password: userPassword,
      roleId: 2,
      birthdate: "2000-01-01",
      updatedAt: now,
    },
  ]);

  await db.insert(skinProfile).values([
    {
      userId: 2,
      skinType: "oily",
      skinSensitivity: "resistant",
      createdAt: now,
    },
  ]);

  await db.insert(skinCareProducts).values([
  {
    id: 1,
    productName: "GENTLE EXFOLIATING SA CLEANSER",
    productBrand: "CETAPHIL",
    productImage: "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dw71f8fecd/302990530162/053016%20Gentle%20Exfol%20SA%20Cleanser%208oz%20-%20Front.PNG?sw=900&sh=900&sm=fit&q=85",
    highlightedIngredients: "Salicylic Acid, Niacinamide",
    ingredient: "Water,Glycerin,Cocamidopropyl Betaine,Coco-Glucoside,Gluconolactone,Betaine,Peg-120 Methyl Glucose Dioleate,Sodium Cocoamphoacetate,Glycereth-26,Salicylic Acid,Sodium Chloride,Panthenol,Niacinamide,Mandelic Acid,Sodium Citrate,Sodium Hydroxide,Helianthus Annuus Sunflower Seed Oil,Tocopherol,Phenoxyethanol,Citric Acid,Ethylhexylglycerin,Disodium Edta,Pantolactone",
    description: "Gently cleanses and exfoliates to promote surface skin cell renewal for smooth, even and radiant-looking skin after just 1 use.",
    productType: "Cleanser",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 2,
    productName: "Moisturizing Cream",
    productBrand: "CETAPHIL",
    productImage: "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dwde5cbd08/Moisturizing%20Cream/052410_MC_16oz-Front.PNG?sw=900&sh=900&sm=fit&q=85",
    highlightedIngredients: "Niacinamide",
    ingredient: "Water, Glycerin, Petrolatum, Dicaprylyl Ether, Dimethicone, Glyceryl Stearate, Cetyl Alcohol, Helianthus Annuus Sunflower Seed Oil, Peg-30 Stearate, Panthenol, Niacinamide, Prunus Amygdalus Dulcis Sweet Almond Oil, Tocopheryl Acetate, Pantolactone, Dimethiconol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Carbomer, Propylene Glycol, Disodium Edta, Benzyl Alcohol, Phenoxyethanol, Sodium Hydroxide, Citric Acid",
    description: "Rich cream clinically proven to hydrate for 48 hours and fully restores skin's moisture barrier.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "dry, sensitive",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 3,
    productName: "Aveeno Skin Relief Lotion 71ml",
    productBrand: "AVEENO",
    productImage: "https://down-ph.img.susercontent.com/file/sg-11134253-7ratx-ma60faxg3etf14.webp",
    highlightedIngredients: "Colloidal Oatmeal",
    ingredient: "Water, Glycerin, Cocamidopropyl Betaine, Sodium Laureth Sulfate, Avena Sativa Oat Kernel Flour, Coriandrum sativum Coriander Fruit/Leaf Extract, Elettaria cardamomum Seed Extract, Commiphora myrrha Leaf Cell Extract, Hydroxypropyltrimonium Hydrolyzed Wheat Protein, Hydroxypropyltrimonium Hydrolyzed Wheat Starch, PEG-20 Almond Glycerides, Guar Hydroxypropyltrimonium Chloride, Tetrasodium EDTA, Glycol Distearate, Polyquaternium-10, Quaternium-15, Myristyl Alcohol, Citric Acid",
    description: "Aveeno Skin Relief Moisturizing Lotion helps heal very dry skin with rich yet fast-absorbing 48-hour moisture.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 4,
    productName: "Daily Moisturizing Cream for Normal to Dry, Sensitive Skin",
    productBrand: "AVEENO",
    productImage: "https://images.ctfassets.net/mgaihfszrtka/2GVCCsvj7jJytsZsLJkhhQ/32ad14317ba8d8f4a736d486da7f0c12/AVE_NA_US_00381372024512_30055387_DailyMoisturizingCream_15oz_994706866_00000.webp?fm=webp&w=1024",
    highlightedIngredients: "Colloidal Oatmeal",
    ingredient: "WATER, GLYCERIN, ISOPROPYL MYRISTATE, CETYL ALCOHOL, CARBOMER, BUTYROSPERMUM PARKII SHEA BUTTER, AVENA SATIVA OAT KERNEL FLOUR, POTASSIUM CETYL PHOSPHATE, CAPRYLYL GLYCOL, SODIUM HYDROXIDE, P-ANISIC ACID, ETHYLHEXYLGLYCERIN",
    description: "Aveeno Daily Moisturizing Lotion nourishes to replenish skin's natural moisture and leaves your skin looking healthy and beautiful.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "dry, sensitive",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 5,
    productName: "PHYSIOGEL Daily Moisture Therapy Cream",
    productBrand: "Physiogel",
    productImage: "https://incidecoder-content.storage.googleapis.com/ff5037ef-cc6f-437c-abfd-65b3a4b38fee/products/physiogel-daily-moisture-therapy-lotion/physiogel-daily-moisture-therapy-lotion_front_photo_300x300@1x.webp",
    highlightedIngredients: "Glycerin, Squalane, Ceramide 3",
    ingredient: "Aqua, Caprylic/Capric Triglyceride, Glycerin, Pentylene Glycol, Cocos Nucifera Oil, Hydrogenated Lecithin, Butyrospermum Parkii Butter, Hydroxyethylcellulose, Squalane, Carbomer, Xanthan Gum, Sodium Carbomer, Ceramide 3",
    description: "Triple-action formula repairs, restores and hydrates dry skin. Provides long-lasting moisture. Helps to make skin less sensitive.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "dry, sensitive",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 6,
    productName: "PHYSIOGEL Daily Moisture Therapy Lotion",
    productBrand: "Physiogel",
    productImage: "https://edge.sitecorecloud.io/zuelligphar3c90-zpcms-prod-4532/media/Project/Physiogel/PhysiogelPhilippines/Product/Daily-Moisture-Therapy-Dermo-Cleanser/Daily-Moisture-Therapy-Dermo-cleanser--150mL.png?h=524&iar=0&w=607",
    highlightedIngredients: "Olea Europaea Fruit Oil, Glycerin, Squalane, Ceramide 3",
    ingredient: "Aqua, Caprylic/Capric Triglyceride, Glycerin, Pentylene Glycol, Cocos Nucifera Oil, Elaeis Guineensis Oil, Butyrospermum Parkii Butter, Olea Europaea Fruit Oil, Hydrogenated Lecithin, Hydroxyethylcellulose, Caprylyl Glycol, Xanthan Gum, Squalane, Carbomer, Sodium Carbomer, Ceramide 3",
    description: "For dry and sensitive skin. Relieves dry tight skin. Makes skin less sensitive. Clinically proven to strengthen and repair the skin's moisture barrier.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 7,
    productName: "Daily Moisture Therapy Dermo-Cleanser",
    productBrand: "Physiogel",
    productImage: "https://edge.sitecorecloud.io/zuelligphar3c90-zpcms-prod-4532/media/Project/Physiogel/PhysiogelPhilippines/Product/Daily-Moisture-Therapy-Dermo-Cleanser/Daily-Moisture-Therapy-Dermo-cleanser--150mL.png?h=524&iar=0&w=607",
    highlightedIngredients: "Disodium Phosphate, Citric Acid",
    ingredient: "Water/Eau, PEG-75, Cetearyl Alcohol, Disodium Phosphate, Sodium Cocoyl Isethionate, Methylparaben, Citric Acid, Butylparaben, Propylparaben, Parfum/Fragrance",
    description: "Non-foaming hypoallergenic face wash that moisturizes the skin. Maintains moisture even after washing. Gentle cleaning power without pulling.",
    productType: "Cleanser",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 8,
    productName: "VASELINE Intensive Care Lotion Deep Restore",
    productBrand: "Vaseline",
    productImage: "https://medias.watsons.com.ph/publishing/WTCPH-10050605-front-zoom.jpg?version=1734046018",
    highlightedIngredients: "Lactic Acid",
    ingredient: "Water; Mineral Oil; Glycerin; Cetostearyl Alcohol; Dihydroxyproptyltrimonium chloride; hydroxyethyl urea; oat extract; sodium cetostearyl sulphate; glyceryl stearate; paraffin; dimethicone; microcrystalline wax; sodium carboxy methyl cellulose; methyl paraben; DMDM hydantoin; propyl paraben; simethicone; disodium edta; soyabean oil; butylated hydroxy toluene; perfume",
    description: "Has micro-droplets of Vaseline Jelly, clinically proven to moisturize deeply within the first application to help heal dry skin.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 9,
    productName: "Retinol 1% in Squalane",
    productBrand: "The Ordinary",
    productImage: "https://theordinary.us.com/cdn/shop/files/rdn-retinol-1pct-in-squalane-30ml.webp?v=1771667469&width=600",
    highlightedIngredients: "Retinol 1%",
    ingredient: "Squalane, Caprylic/Capric Triglyceride, Simmondsia Chinensis Jojoba Seed Oil, Retinol 1.0%, Solanum Lycopersicum Tomato Fruit Extract, Rosmarinus Officinalis Rosemary Leaf Extract, Hydroxymethoxyphenyl Decanone, BHT",
    description: "Water-free solution containing 1% retinol that improves the appearance of fine lines, skin texture and tone.",
    productType: "Serum",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Night",
    updatedAt: now,
  },
  {
    id: 10,
    productName: "Salicylic Acid Daily Gentle Cleanser",
    productBrand: "CosrRx",
    productImage: "https://m.media-amazon.com/images/I/61ic3PbK8oL._SX466_.jpg",
    highlightedIngredients: "Salicylic Acid",
    ingredient: "Water, Glycerin, Myristic Acid, Stearic Acid, Potassium Hydroxide, Lauric Acid, Butylene Glycol, Glycol Distearate, Polysorbate 80, Salix Alba Bark Water, Sodium Methyl Cocoy Taurate, Cocamidopropyl Betaine, PEG-60 Hydrogenated Castor Oil Salicylic Acid, Limonene, Citrus Limon Peel Oil, Citric Acid, Melaleuca Alternifolia Leaf Oil, Sodium Chloride, Disodium EDTA, 1,2-Hexandiol, Ethyl Hexanediol, Caprylyl Glycol, Ethylhexylglycerin",
    description: "Nourishing cleansing wash with Tea Tree Oil, Willow Bark Water and 0.5% Salicylic Acid that helps treat and prevent breakouts.",
    productType: "Cleanser",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 11,
    productName: "The Retinol 0.1 Cream",
    productBrand: "CosrRx",
    productImage: "https://www.cosrx.com/cdn/shop/files/RetinolCream_800x1067_7e167f9b-dc45-4d41-babf-65b26b14cf23_720x.jpg?v=1746679017",
    highlightedIngredients: "Retinol 0.1%",
    ingredient: "Water/Aqua/Eau, Caprylic/Capric Triglyceride, Propanediol, Glycerin, Tocopheryl Acetate, Cetearyl Alcohol, Trehalose, Panthenol, Butyrospermum Parkii Shea Butter, Glycine Soja Soybean Oil, Dimethicone, Retinol, Allantoin, Sodium Hyaluronate, Hyaluronic Acid",
    description: "0.1% pure retinol with low irritation. Ideal for first-time retinol users looking to prevent and correct early signs of aging.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Night",
    updatedAt: now,
  },
  {
    id: 12,
    productName: "Low pH Good Morning Gel Cleanser",
    productBrand: "CosrRx",
    productImage: "https://www.cosrx.com/cdn/shop/files/low-ph-good-morning-gel-cleanser-cosrx-official-1_720x.jpg?v=1768785801",
    highlightedIngredients: "Betaine Salicylate, Tea Tree Oil",
    ingredient: "Water, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Sodium Chloride, Polysorbate 20, Butylene Glycol, Saccharomyces Ferment, Melaleuca Alternifolia Tea Tree Leaf Oil, Allantoin, Caprylyl Glycol, Ethylhexylglycerin, Betaine Salicylate, Citric Acid, 1,2-Hexanediol, Sodium Benzoate, Disodium EDTA",
    description: "While refining skin texture, this cleanser helps cleanse with no stripping. Great for all skin types.",
    productType: "Cleanser",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 13,
    productName: "5 PDRN Hyaluronic Acid Vital Hydrating Hydrogel Mask",
    productBrand: "CosrRx",
    productImage: "https://koreanskincare.com/cdn/shop/files/Cosrx_5PDRNHyaluronicAcidVitalHydratingHydrogelMask_Packshot.jpg?v=1772526486",
    highlightedIngredients: "Hyaluronic Acid",
    ingredient: "Water, Glycerin, Acrylates Copolymer, Niacinamide, 1,2-Hexanediol, Sodium Hyaluronate, Cellulose Gum, Panthenol, Allantoin, Xanthan Gum, Alpha-Arbutin, Centella Asiatica Extract, Hydrolyzed Hyaluronic Acid, Hyaluronic Acid, Sodium Hyaluronate Crosspolymer, Tocopherol",
    description: "Ultra-soothing deeply replenishing mask designed to deliver instant and long-lasting hydration.",
    productType: "Serum",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "dry, sensitive",
    dermaTested: true,
    timeRoutine: "Night",
    updatedAt: now,
  },
  {
    id: 14,
    productName: "Aloe Soothing Sun Cream SPF50+/ PA+++",
    productBrand: "CosrRx",
    productImage: "https://www.cosrx.com/cdn/shop/files/aloe-soothing-sun-cream-spf50-pa-cosrx-official-1_720x.jpg?v=1724835559",
    highlightedIngredients: "Aloe Complex 55,000ppm",
    ingredient: "WATER, ETHYLHEXYL METHOXYCINNAMATE, GLYCERIN, PROPYLENE GLYCOL, CYCLOPENTASILOXANE, PHENYLBENZIMIDAZOLE SULFONIC ACID, DIMETHICONE, BUTYLENE GLYCOL, GLYCERYL STEARATE, TITANIUM DIOXIDE, ALOE ARBORESCENS LEAF EXTRACT, DIPOTASSIUM GLYCYRRHIZATE, CARBOMER, XANTHAN GUM, TOCOPHERYL ACETATE, DISODIUM EDTA",
    description: "Formulated with Aloe Arborescens Leaf Extract. Lightweight daily soothing sunblock that feels like a moisturizer with no white cast.",
    productType: "Sunscreen",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 15,
    productName: "Aloe 54.2 Aqua Tone-up Sunscreen SPF 50+ PA++++",
    productBrand: "CosrRx",
    productImage: "https://www.cosrx.com/cdn/shop/files/aloe-54-2-aqua-tone-up-sunscreen-spf-50-pa-cosrx-official-1_720x.jpg?v=1724836911",
    highlightedIngredients: "Niacinamide, Hyaluronic Acid, Allantoin",
    ingredient: "Aloe Barbadensis Leaf Water, Homosalate, Butylene Glycol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Salicylate, Glycerin, Water, Niacinamide, Titanium Dioxide, Sodium Hyaluronate, Allantoin, Cyanocobalamin, Tocopherol",
    description: "Infused with aloe barbadensis leaf water, lightweight sunscreen that protects against UV rays and soothes sunburn.",
    productType: "Sunscreen",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 16,
    productName: "Advanced The Vitamin C 23 Serum",
    productBrand: "CosrRx",
    productImage: "https://www.cosrx.com/cdn/shop/files/Advanced_VitaminC23_00_900x.webp?v=1760935746",
    highlightedIngredients: "Vitamin C",
    ingredient: "Aqua/Water, Ascorbic Acid 23%, Butylene Glycol, Dimethicone, Panthenol, 3-O-Ethyl Ascorbic Acid, Squalane, Sodium Hydroxide, Caffeine, Sodium Hyaluronate, Adenosine, Niacinamide, Pentylene Glycol, Glutathione, Helianthus Annuus Sunflower Seed Oil",
    description: "High strength 23% pure vitamin C with Super Vitamin E and Glutathione to target uneven skin tone, early signs of aging, and dullness.",
    productType: "Serum",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 17,
    productName: "The Vitamin C 13 Serum",
    productBrand: "CosrRx",
    productImage: "https://www.cosrx.com/cdn/shop/files/The_VitaminC13_00_720x.webp?v=1762850506",
    highlightedIngredients: "Vitamin C",
    ingredient: "Water, Ascorbic Acid 13%, Butylene Glycol, Dipropylene Glycol, Tromethamine, 3-0-Ethyl Ascorbic Acid, Panthenol, Caffeine, Sodium Hyaluronate, Glutathione, Adenosine, Squalane, Niacinamide, Pentylene Glycol, Glycyrrhiza Glabra Licorice Root Extract",
    description: "Gentle water-based vitamin C serum that provides moisture and absorbs quickly. Regular use fades blemishes, dark spots, and freckles.",
    productType: "Serum",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 18,
    productName: "Dermocycling Antiaging Serum 1% Retinol Complex",
    productBrand: "Bioten",
    productImage: "https://biotencosmetics.com/userfiles/products/DERMOCYCLING%20FACE%20SERUMS%202025/BIOTEN-DERM-RETINOL-SERUM-_SET-[RGB].png?h=500&quality=75",
    highlightedIngredients: "Retinol 1%",
    ingredient: "ISOPROPYL PALMITATE, DIBUTYL ADIPATE, UNDECANE, SQUALANE, TRIGLYCERIDE, PARFUM, RETINYL PALMITATE",
    description: "Bioten RETINOL Face Serum with 1% Retinol Complex regenerates skin, reduces wrinkles and increases elasticity.",
    productType: "Serum",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Night",
    updatedAt: now,
  },
  {
    id: 19,
    productName: "Skin Moisture Face Cream dry/sensitive skin",
    productBrand: "Bioten",
    productImage: "https://biotencosmetics.com/userfiles/products/FACELIFT/Skin%20Moisture%20Dry.png?h=500&quality=75",
    highlightedIngredients: "Ascorbic Acid",
    ingredient: "Aqua, Dimethicone, Glycerin, Phenyl Trimethicone, Caprylic/Capric Triglyceride, Sodium Acrylates Copolymer, Propanediol, Crocus Sativus Flower Extract, Hydrolyzed Soy Protein, Sodium Hyaluronate, Allantoin, Ascorbic Acid, Ascorbyl Palmitate, Panthenol, Tocopherol, Tocopheryl Acetate, Urea, Xanthan Gum",
    description: "SKIN MOISTURE face cream for dry/sensitive skin with 100% natural Saffron extract and Prebiotics. Hydrates skin for up to 24 hours.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 20,
    productName: "Skin Moisture Face Cream",
    productBrand: "Bioten",
    productImage: "https://biotencosmetics.com/userfiles/products/FACELIFT/Skin%20Moisture%20Normal.png?h=500&quality=75",
    highlightedIngredients: "Ascorbic Acid",
    ingredient: "Aqua, Glycerin, C13-15 Alkane, Phenyl Trimethicone, Sodium Acrylates Copolymer, Propanediol, Hydrolyzed Soy Protein, Sodium Hyaluronate, Allantoin, Ascorbic Acid, Ascorbyl Palmitate, Panthenol, Tocopherol, Tocopheryl Acetate, Urea, Xanthan Gum",
    description: "SKIN MOISTURE face cream for normal skin with 100% natural Quince extract and Prebiotics. Provides moisture for up to 24 hours.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 21,
    productName: "SKIN GLOW Brightening Face UV fluid SPF 50+",
    productBrand: "Bioten",
    productImage: "https://biotencosmetics.com/userfiles/products/FACE%20UV%20FLUIDS%202025/BIOT-SKIN-GLOW-FLUID-50ml-_SET.png?h=500&quality=75",
    highlightedIngredients: "Niacinamide, Tranexamic Acid, Bakuchiol",
    ingredient: "Aqua, Diisopropyl Adipate, Octocrylene, C12-15 Alkyl Benzoate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Glycerin, Niacinamide, Bakuchiol, Allantoin, Panthenol, Tocopherol, Tocopheryl Acetate, Tranexamic Acid",
    description: "Bioten SKIN GLOW Brightening Face UV fluid SPF 50+ helps prevent photoaging. Improves uneven skin tone and reduces skin pigmentation.",
    productType: "Sunscreen",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 22,
    productName: "Glow Expert 4D Face Fluid SPF50+",
    productBrand: "Bioten",
    productImage: "https://biotencosmetics.com/userfiles/products/FACE%20UV%20FLUIDS%202025/BIOT-GLOW-EXP-FLUID-50ml-_SET%20(1.png?h=500&quality=75",
    highlightedIngredients: "Niacinamide, Tranexamic Acid, Bakuchiol",
    ingredient: "Aqua, Diisopropyl Adipate, Octocrylene, C12-15 Alkyl Benzoate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Glycerin, Niacinamide, Bakuchiol, Allantoin, Panthenol, Tocopherol, Tocopheryl Acetate, Tranexamic Acid",
    description: "Bioten GLOW EXPERT 4D Anti Dark Spot and Antiwrinkle Face UV fluid SPF 50+. Even skin tone, dark spot reduction, antiwrinkle action.",
    productType: "Sunscreen",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 23,
    productName: "Hyaluronic Gold UV Fluid Face Cream SPF50+",
    productBrand: "Bioten",
    productImage: "https://biotencosmetics.com/userfiles/products/FACE%20UV%20FLUIDS%202025/BIOT-HYAL-GOLD-FLUID-50ml-_SET%20(1.png?h=500&quality=75",
    highlightedIngredients: "Hyaluronic Acid, Glycerin, Allantoin, Vitamin E",
    ingredient: "Aqua, Diisopropyl Adipate, Octocrylene, Glycerin, Hydrolyzed Sodium Hyaluronate, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Sodium Hyaluronate Crosspolymer, Allantoin, Panthenol, Tocopherol",
    description: "Bioten HYALURONIC GOLD replumping antiwrinkle Face UV fluid SPF 50+ with 5 types of Hyaluronic Acid for advanced filling and plumping action.",
    productType: "Sunscreen",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, dry",
    dermaTested: true,
    timeRoutine: "Morning",
    updatedAt: now,
  },
  {
    id: 24,
    productName: "CeraVe Moisturizing Cream",
    productBrand: "CeraVe",
    productImage: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v4/moisturizing-cream/cerave_moisturizing_cream_16oz_jar_front-700x875-v4.jpg?rev=db6e3c22250e4928bc749dd2c207de5b&w=900&hash=E68F77D279494CD09396613CB8496EB7",
    highlightedIngredients: "Tocopherol, Phytosphingosine, Glycerin, Ceramide",
    ingredient: "Aqua, Glycerin, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Cetyl Alcohol, Ceteareth-20, Petrolatum, Potassium Phosphate, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Dimethicone, Behentrimonium Methosulfate, Sodium Lauroyl Lactylate, Sodium Hyaluronate, Cholesterol, Phenoxyethanol, Disodium EDTA, Dipotassium Phosphate, Tocopherol, Phytosphingosine, Xanthan Gum, Ethylhexylglycerin",
    description: "Rich non-greasy moisturizer with ceramides that absorbs quickly to help soothe dry, itchy skin while restoring the skin's natural protective barrier.",
    productType: "Moisturizer",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "dry, sensitive",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 25,
    productName: "CeraVe Foaming Cleanser",
    productBrand: "CeraVe",
    productImage: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/cleansers/foaming-facial-cleanser/photos/2026/700x785/ffc-atf-1-700x785-v1.jpg?rev=f0923e1e888a44b5ac66d4bb8025218a&w=900&hash=797592F77DE7ED4A52F19EE16DAA83F0",
    highlightedIngredients: "Phytosphingosine, Glycerin, Ceramide",
    ingredient: "Purified Water, Glycerin, Behentrimonium Methosulfate, Cetearyl Alcohol, Ceramide 3, Ceramide 6 II, Ceramide 1, Hyaluronic Acid, Cholesterol, Glyceryl Monostearate, Stearyl Alcohol, Potassium Phosphate, Dipotassium Phosphate, Sodium Lauroyl Lactylate, Cetyl Alcohol, Disodium EDTA, Phytosphingosine, Carbomer, Xanthan Gum",
    description: "Foaming facial cleanser with ceramides, hyaluronic acid, and niacinamide that maintains skin's protective barrier and locks in moisture.",
    productType: "Cleanser",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 26,
    productName: "CeraVe SA Smoothing Cleanser",
    productBrand: "CeraVe",
    productImage: "https://incidecoder-content.storage.googleapis.com/48091d69-2d2b-4fd1-bdef-8525fa21eed7/products/cerave-sa-smoothing-cleanser/cerave-sa-smoothing-cleanser_front_photo_300x300@1x.webp",
    highlightedIngredients: "Niacinamide, Salicylic Acid, Phytosphingosine",
    ingredient: "Aqua/Water, Sodium Lauroyl Sarcosinate, Cocamidopropyl Hydroxysultaine, Glycerin, Niacinamide, Gluconolactone, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Salicylic Acid, Sodium Benzoate, Sodium Lauroyl Lactylate, Cholesterol, Phenoxyethanol, Disodium EDTA, Hydrolyzed Hyaluronic Acid, Phytosphingosine, Xanthan Gum, Ethylhexylglycerin",
    description: "Provides gentle non-irritating exfoliation with three essential ceramides, hyaluronic acid and niacinamide without disrupting skin's protective barrier.",
    productType: "Cleanser",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
  {
    id: 27,
    productName: "CeraVe Acne Control Gel",
    productBrand: "CeraVe",
    productImage: "https://incidecoder-content.storage.googleapis.com/e59269c5-ed06-4c74-8824-a81879b40915/products/cerave-acne-control-gel/cerave-acne-control-gel_front_photo_300x300@1x.webp",
    highlightedIngredients: "Salicylic Acid, Niacinamide, Glycolic Acid, Phytosphingosine",
    ingredient: "Aqua/Water, Glycerin, Sodium Hydroxide, Glycolic Acid, Lactic Acid, Salicylic Acid, Niacinamide, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Cetearyl Alcohol, Behentrimonium Methosulfate, Sodium Hyaluronate, Sodium Lauroyl Lactylate, Cholesterol, Chlorphenesin, Disodium EDTA, Caprylyl Glycol, Xanthan Gum, Phytosphingosine, Benzoic Acid",
    description: "Hydrating daily acne treatment with 2% salicylic acid that clears acne and helps prevent new breakouts from forming.",
    productType: "Serum",
    locality: "International",
    availableIn: "Shopee, Watson",
    skinType: "oily, sensitive, combination",
    dermaTested: true,
    timeRoutine: "Morning, Night",
    updatedAt: now,
  },
]);
  await db.insert(conditionProducts).values([
  // blackheads/whiteheads/milia/enlarged pores → products 1,9,10,11,18,26,27
  { conditionId: 1, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 1, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 1, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 1, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 1, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 1, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 1, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 2, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 3, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 4, productId: 27, createdAt: now, updatedAt: now },

  // papules/pustules → products 9,11,18,27
  { conditionId: 5, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 5, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 5, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 5, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 6, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 6, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 6, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 6, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 7, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 7, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 7, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 7, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 8, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 8, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 8, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 8, productId: 27, createdAt: now, updatedAt: now },

  // eczema → products 2,3,4,5,6,8,19,20,24
  { conditionId: 9, productId: 2, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 3, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 4, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 5, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 6, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 8, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 19, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 20, createdAt: now, updatedAt: now },
  { conditionId: 9, productId: 24, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 2, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 3, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 4, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 5, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 6, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 8, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 19, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 20, createdAt: now, updatedAt: now },
  { conditionId: 10, productId: 24, createdAt: now, updatedAt: now },

  // melasma → products 14,15,16,17,21,22,23,27
  { conditionId: 11, productId: 14, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 15, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 21, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 22, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 23, createdAt: now, updatedAt: now },
  { conditionId: 11, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 14, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 15, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 21, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 22, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 23, createdAt: now, updatedAt: now },
  { conditionId: 12, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 14, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 15, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 21, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 22, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 23, createdAt: now, updatedAt: now },
  { conditionId: 13, productId: 27, createdAt: now, updatedAt: now },

  // milia → products 1,9,10,11,18,26,27
  { conditionId: 14, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 14, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 14, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 14, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 14, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 14, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 14, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 15, productId: 27, createdAt: now, updatedAt: now },

  // enlarged pores → products 1,9,10,11,18,26,27
  { conditionId: 16, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 16, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 16, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 16, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 16, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 16, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 16, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 1, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 9, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 10, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 11, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 18, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 26, createdAt: now, updatedAt: now },
  { conditionId: 17, productId: 27, createdAt: now, updatedAt: now },

  // post-inflammatory pigmentation → products 14,15,16,17,21,22,23,27
  { conditionId: 18, productId: 14, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 15, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 21, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 22, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 23, createdAt: now, updatedAt: now },
  { conditionId: 18, productId: 27, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 14, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 15, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 21, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 22, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 23, createdAt: now, updatedAt: now },
  { conditionId: 19, productId: 27, createdAt: now, updatedAt: now },

  // post-inflammatory erythema → products 16,17,21
  { conditionId: 20, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 20, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 20, productId: 21, createdAt: now, updatedAt: now },
  { conditionId: 21, productId: 16, createdAt: now, updatedAt: now },
  { conditionId: 21, productId: 17, createdAt: now, updatedAt: now },
  { conditionId: 21, productId: 21, createdAt: now, updatedAt: now },
]);

  console.log("Seeding completed!");
}

try {
  await main();
  process.exit(0);
} catch (e) {
  console.error(e);
  process.exit(1);
}
